/**
 * Content helpers — typed access to Velite-generated lesson data.
 *
 * Velite processes MDX files at build time and outputs typed JSON to .velite/.
 * Import from "@/.velite" which resolves to pe-academy/.velite/index.ts
 * (generated by `velite build` during the Next.js webpack build).
 *
 * These functions are safe to call from React Server Components.
 */

// NOTE: .velite/index.ts is generated at build time by velite.
// If your IDE shows a "module not found" error before the first build, run
// `npx velite build` once to generate the output, then the types will resolve.
import { lessons } from "@/.velite";

export function getLessons() {
  return lessons;
}

export function getLessonBySlug(moduleSlug: string, lessonSlug: string) {
  return lessons.find(
    (l) => l.module === moduleSlug && l.slugAsParams === lessonSlug
  );
}

export function getLessonsByModule(moduleSlug: string) {
  return lessons
    .filter((l) => l.module === moduleSlug)
    .sort((a, b) => a.order - b.order);
}

export function getLessonsByLevel(level: number) {
  return lessons
    .filter((l) => l.level === level)
    .sort((a, b) => a.order - b.order);
}

export function getModuleSlugs() {
  return [...new Set(lessons.map((l) => l.module))];
}
